// Static seed content mirrored from the Marquee design deck
// (project/Marquee - Event Platform.dc.html — Discovery, Event Details, Attendees & Door slides).

export const workspaceSeed = {
  name: "Warehouse 09",
  avatarInitial: "W",
  avatarColor: "#FF4D8D",
  ownerName: "Rina Kessler",
  ownerRole: "Owner",
  ownerInitials: "RK",
};

// Demo attendee used for the un-authenticated "My Tickets" wallet + checkout contact prefill.
export const demoAttendee = {
  name: "Amara Okafor",
  email: "amara.okafor@gmail.com",
};

// today/tonight is resolved at seed time relative to `new Date()`.
export const eventDefs = [
  {
    key: "neon-nights",
    title: "Neon Nights",
    slug: "neon-nights",
    lineup: "Blawan · Anfisa · SPFDJ · Kobosil",
    genre: "Techno",
    vibe: ["Warehouse"],
    city: "Berlin",
    venue: "Warehouse 09",
    neighborhood: "Kreuzberg",
    dayOffset: 0,
    startHour: 23,
    endHour: 6,
    doorsTimeLabel: "11 PM–6 AM",
    ageRestriction: "18+",
    heroGradient: { from: "#6B4EFF", to: "#2A1C6E" },
    badge: "Selling fast",
    description:
      "Warehouse 09 opens its main room and a second concrete cellar for eight hours of unbroken techno. Blawan headlines with a live hardware set; SPFDJ and Anfisa trade the closing hours. Brutalist space, Funktion-One rig, strictly no phones on the floor.",
    amenities: ["🔊 Funktion-One", "🚭 No phones", "🪪 ID required", "🅿️ No re-entry"],
    viewCount: 42900,
    checkoutStarts: 2140,
    // Sold counts are reconciled in seed.js against the door monitor (380 total,
    // 312 checked in across Gate A/Gate B/VIP entrance) — see `plan` in seed.js.
    tiers: [
      { name: "General Admission", description: "Entry all night", price: 18, quantityTotal: 306, quantitySold: 266 },
      { name: "GA + Fast Track", description: "Skip the queue", price: 28, quantityTotal: 120, quantitySold: 90 },
      { name: "VIP Balcony", description: "Private bar · seated", price: 60, quantityTotal: 24, quantitySold: 24 },
    ],
  },
  {
    key: "pulse-rooftop",
    title: "Pulse Rooftop",
    slug: "pulse-rooftop",
    lineup: "Peggy Gou (b2b) · HAAi",
    genre: "House",
    vibe: ["Rooftop"],
    city: "Berlin",
    venue: "Klunkerkranich",
    neighborhood: "Neukölln",
    dayOffset: -1,
    startHour: 22,
    endHour: 4,
    doorsTimeLabel: "10 PM",
    ageRestriction: "18+",
    heroGradient: { from: "#FF4D8D", to: "#8A1E4A" },
    badge: "6 LEFT",
    description:
      "Sunset-to-sunrise on the Neukölln rooftop. Peggy Gou and HAAi trade a five-hour back-to-back over the city skyline before the last train.",
    amenities: ["🌇 Rooftop views", "🪪 ID required", "🍸 Full bar"],
    viewCount: 31500,
    checkoutStarts: 1860,
    tiers: [
      { name: "General Admission", description: "Entry all night", price: 32, quantityTotal: 320, quantitySold: 314 },
    ],
  },
  {
    key: "bassline",
    title: "Bassline",
    slug: "bassline",
    lineup: "Objekt · Batu · Ploy",
    genre: "Techno",
    vibe: ["Warehouse"],
    city: "Berlin",
    venue: "Griessmuehle",
    neighborhood: "Alt-Treptow",
    dayOffset: 0,
    startHour: 21,
    endHour: 5,
    doorsTimeLabel: "9 PM",
    ageRestriction: "18+",
    heroGradient: { from: "#21C1B6", to: "#0C5D57" },
    badge: "",
    description:
      "Left-field bass and broken techno across two rooms. Objekt headlines a rare Berlin date, with Batu and Ploy opening and closing.",
    amenities: ["🔊 Funktion-One", "🪪 ID required"],
    viewCount: 18200,
    checkoutStarts: 640,
    tiers: [
      { name: "General Admission", description: "Entry all night", price: 15, quantityTotal: 260, quantitySold: 88 },
    ],
  },
  {
    key: "golden-hour",
    title: "Golden Hour",
    slug: "golden-hour",
    lineup: "Open air · day & night",
    genre: "Techno",
    vibe: ["Intimate"],
    city: "Berlin",
    venue: "Sisyphos",
    neighborhood: "Friedrichshain",
    dayOffset: 2,
    startHour: 14,
    endHour: 23,
    doorsTimeLabel: "2 PM",
    ageRestriction: "18+",
    heroGradient: { from: "#FFA23A", to: "#93500A" },
    badge: "",
    description:
      "Open-air day party that runs straight into the night — sun loungers, three sound systems, and no set curfew.",
    amenities: ["☀️ Open air", "🍸 Full bar", "🪪 ID required"],
    viewCount: 54200,
    checkoutStarts: 3010,
    tiers: [
      { name: "General Admission", description: "Entry all day", price: 22, quantityTotal: 600, quantitySold: 540 },
    ],
  },
  {
    key: "velvet-room",
    title: "Velvet Room",
    slug: "velvet-room",
    lineup: "Intimate · minimal",
    genre: "House",
    vibe: ["Intimate"],
    city: "Berlin",
    venue: "://about blank",
    neighborhood: "Friedrichshain",
    dayOffset: -1,
    startHour: 23,
    endHour: 6,
    doorsTimeLabel: "11 PM",
    ageRestriction: "18+",
    heroGradient: { from: "#8B7CFF", to: "#4B3EA8" },
    badge: "",
    description: "A small room built for a long, minimal night. No lineup announced until the door — that's the point.",
    amenities: ["🔊 Minimal rig", "🪪 ID required"],
    viewCount: 22100,
    checkoutStarts: 980,
    tiers: [
      { name: "General Admission", description: "Entry all night", price: 20, quantityTotal: 260, quantitySold: 205 },
    ],
  },
  {
    key: "after-dark",
    title: "After Dark",
    slug: "after-dark",
    lineup: "All night · no phones",
    genre: "Techno",
    vibe: ["Warehouse"],
    city: "Berlin",
    venue: "Berghain",
    neighborhood: "Friedrichshain",
    dayOffset: 0,
    startHour: 0,
    endHour: 10,
    doorsTimeLabel: "12 AM",
    ageRestriction: "18+",
    heroGradient: { from: "#2C2A34", to: "#08070B" },
    badge: "",
    description: "All night, no phones. The floor doesn't stop until well past sunrise.",
    amenities: ["🚭 No phones", "🪪 ID required", "🅿️ No re-entry"],
    viewCount: 61800,
    checkoutStarts: 3760,
    tiers: [
      { name: "General Admission", description: "Entry all night", price: 25, quantityTotal: 1400, quantitySold: 1200 },
    ],
  },
];

// Named attendees for Neon Nights, matching the Attendees & Door slide exactly.
export const neonNightsAttendees = [
  {
    name: "Amara Okafor",
    email: "amara.okafor@gmail.com",
    tierName: "General Admission",
    quantity: 2,
    codes: ["MQ-8F2K", "MQ-8F2L"],
    checkedIn: true,
    checkedInAt: { hour: 23, minute: 18 },
    gate: "Gate A · main",
  },
  {
    name: "Diego Fuentes",
    email: "d.fuentes@proton.me",
    tierName: "VIP Balcony",
    quantity: 1,
    codes: ["MQ-2QL9"],
    checkedIn: true,
    checkedInAt: { hour: 23, minute: 24 },
    gate: "VIP entrance",
  },
  {
    name: "Priya Nair",
    email: "priya.nair@gmail.com",
    tierName: "General Admission",
    quantity: 1,
    codes: ["MQ-7XR4"],
    checkedIn: false,
    gate: null,
  },
  {
    name: "Lukas Meyer",
    email: "lukas.m@web.de",
    tierName: "General Admission",
    quantity: 3,
    codes: ["MQ-4KD1", "MQ-4KD2", "MQ-4KD3"],
    checkedIn: true,
    checkedInAt: { hour: 22, minute: 52 },
    gate: "Gate A · main",
  },
  {
    name: "Tomas Silva",
    email: "tsilva@gmail.com",
    tierName: "General Admission",
    quantity: 1,
    codes: ["MQ-9BW2"],
    refunded: true,
  },
];

// Amara Okafor's payment history, matching the My Tickets / payment history slide.
export const demoAttendeeOrders = [
  { eventKey: "neon-nights", tierName: "General Admission", quantity: 2, total: 39.0, method: "Visa ···4471", daysAgo: 4, status: "paid" },
  { eventKey: "golden-hour", tierName: "General Admission", quantity: 1, total: 22.0, method: "Apple Pay", daysAgo: 8, status: "paid" },
  { eventKey: "bassline", tierName: "General Admission", quantity: 1, total: 15.0, method: "Visa ···4471", daysAgo: 20, status: "refunded" },
];
